spring:
  application:
    name: employee-service
eureka:
  client:
    register-with-eureka: true
  instance:
    prefer-ip-address: true
management:
  endpoints:
    web:
      exposure:
        include: info, beans
server:
  port: 8082
